### ISSUE TITLE
Compatibility with http >=0.12.0

### ISSUE THREAD

**Issue by McCossum** [ajwtech/DataKick_SDK#1]
Because every version of datakick_sdk depends on http ^0.11.3+17 and XXX depends on http >=0.12.0 <1.0.0, datakick_sdk is incompatible with XXX

Almost all Flutter packages require http >=0.12.0 but upgrading to 0.12.0 breaks datakick_sdk

**Comment by ajwtech** [comment]
I'm working on this for you now. I almost forgot I created this sdk. It is still not completely rounded out but does what I needed it to do. I'd like to expand it more if you have any suggestions let me know.

**Comment by ajwtech** [comment]
This is resolved now. All dependencies have been updated as needed based on releases for flutter.

**Comment by McCossum** [comment]
Thank you for the quick response to this. It works great!
